# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0002_auto_20181004_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.AlterUniqueTogether(
            name='choicetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='choicetranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='polltranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='polltranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='pollpluginmodel',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypolls.Poll'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='ChoiceTranslation',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollTranslation',
        ),
    ]
