# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choicetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='choicetranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='polltranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='polltranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='', max_length=200, verbose_name='Choice content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='', max_length=200, verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChoiceTranslation',
        ),
        migrations.DeleteModel(
            name='PollTranslation',
        ),
    ]
